#!/usr/bin/env python
"""Render validated reviewer analyses; called by the paper's number generator."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
LABEL={'olmo2-7b-it':'OLMo-2-7B','llama32-3b-it':'Llama-3.2-3B','llama31-8b-it':'Llama-3.1-8B',
 'olmo2-1b-it':'OLMo-2-1B','gemma3-4b-it':'Gemma-3-4B','codegemma-7b-it':'CodeGemma-7B','codellama-7b-it':'CodeLlama-7B'}

def ci(x):
    return '--' if x is None else f'{100*x[0]:.1f} [{100*x[1]:.1f}, {100*x[2]:.1f}]'

def table(lines,columns,header,rows,caption,label):
    lines.extend([r'\begin{table*}[t]',r'\centering\small',r'\sbox{\roundfivebox}{\begin{tabular}{@{}'+columns+r'@{}}',r'\toprule',header+r' \\',r'\midrule'])
    lines.extend(' & '.join(row)+r' \\' for row in rows)
    lines.extend([r'\bottomrule',r'\end{tabular}}',r'\ifdim\wd\roundfivebox>\textwidth\resizebox{\textwidth}{!}{\usebox{\roundfivebox}}\else\usebox{\roundfivebox}\fi',r'\caption{'+caption+'}',r'\label{'+label+'}',r'\end{table*}'])

def load(name):
    p=ROOT/'results/summary'/f'round5_{name}.json'
    if not p.exists():return None
    x=json.loads(p.read_text())
    if not x.get('validated'):raise ValueError(f'unvalidated follow-up {p}')
    return x

def narrative_numbers():
    out={}
    x=load('error_probes')
    if x:
        rates=[]
        for model,tag in (('olmo2-7b-it','olmo7'),('llama32-3b-it','llama3'),('llama31-8b-it','llama8')):
            value=x['models'][model]['pooled']['lure_write']['accuracy_ci95']
            rates.append(value[0])
            for field,rate in zip(('accuracy','lo','hi'),value):out[f'errorprobe-{tag}-{field}']=f'{100*rate:.1f}'
        out['errorprobe-min']=f'{100*min(rates):.1f}'
        out['errorprobe-max']=f'{100*max(rates):.1f}'
        out['errorprobe-prefix-n']=f"{sum(r['n_prefix_match'] for r in x['models'].values()):,}"
    x=load('formats')
    if x:
        for model,tag in (('olmo2-7b-it','olmo7'),('llama32-3b-it','llama3')):
            for kind,label in (('neutral_annotation','annotation'),('numeric_elaboration','numeric')):
                for field,rate in zip(('mean','lo','hi'),x['models'][model][kind]['excess_ci95']):
                    out[f'format-{tag}-{label}-{field}']=f'{100*rate:.1f}'
    return out

def main():
    lines=[r'% Generated by scripts/77_followup_tables.py from validated JSON.',r'\newsavebox{\roundfivebox}']
    x=load('error_probes')
    if x:
        coverage=sum(r['n_prefix_match'] for r in x['models'].values());total=sum(r['n_total'] for r in x['models'].values())
        lines.extend([r'\section{Generated-prefix audit and initial readouts}',r'\label{app:round5-errors}',
            f'For {coverage} of {total} misleading-name generations, the token prefix through the marker before the first value exactly matches the cached trace. This verifies that the cached state at that marker also precedes the generated value. No target value token is included.',
            'These initial readouts select layers on the full neutral evaluation set; the main text instead uses independent cross-fitted selection (Appendix~\\ref{app:round6-probes}). We split the generated writes into name-suggested values, correct values and other errors. Table~\\ref{tab:round5-errors} averages three probe seeds and pools demonstration sets 7, 11 and 13. Intervals resample matched programs with all their demonstration repeats (4,000 draws). These conditional readouts establish available information on observed errors; they do not establish its causal use.'])
        rows=[]
        for m,d in x['models'].items():
            for group,r in d['pooled'].items():rows.append([LABEL[m],{'lure_write':'name error','correct_write':'correct write','other_error':'other error'}[group],str(r['n']),str(r['n_sets']),ci(r['accuracy_ci95'])])
        table(lines,'llrrl','Model & Generated write & Rows & Programs & True-digit accuracy (\\%)',rows,
            'Disjoint probes at the verified generated prefix. A dash denotes an empty stratum. The denominator is observed writes within each stratum, not independent demonstration repeats.','tab:round5-errors')
    x=load('identifiers')
    if x:
        passed=[name for name,p in x['panel_pass'].items() if p]
        lines.extend([r'\section{Sensitivity to identifier meanings}',r'\label{app:round5-identifiers}',
            ('None of the three main-cell names (\\texttt{total}, \\texttt{sum\\_all}, \\texttt{acc}) meets the originally planned 80\\% panel gate. Its filtered estimate is therefore unavailable, rather than zero.' if not passed else 'The original panel gate is applied without selecting names by the measured effect.'),
            'Table~\\ref{tab:round5-identifiers} retains the full-data estimate and reports each name and each model\'s own meaning gate. Gates use the original saved meaning checks. Intervals cluster matched programs across the three demonstration sets. This exploratory sensitivity does not replace the planned panel gate or remove the deviation from it.'])
        rows=[]
        for m,d in x['models'].items():rows.append([LABEL[m]]+[ci(d['subsets'][k]['excess_ci95']) for k in ('all','model_gate','total','sum_all','acc')])
        table(lines,'llllll',r'Model & All & Model gate & \texttt{total} & \texttt{sum\_all} & \texttt{acc}',rows,
            'Excess name errors in percentage points [95\\% interval], level 5 length-to-sum. Empty subsets are shown as dashes. The saved JSON also reports each demonstration set and the all-three-sets sign rule.','tab:round5-identifiers')
    x=load('formats')
    if x:
        lines.extend([r'\section{Length and numeric elaboration controls}',r'\label{app:round5-formats}',
            'We add neutral annotations to each demonstrated value, matching the expression demonstrations\' token counts, and separately add valid numeric elaborations of the form \\texttt{name = value + 0 = value}. The test program and \\texttt{Trace:} prefix are unchanged. Greedy decoding uses the same 285 misleading programs and neutral twins for each format. Table~\\ref{tab:round5-formats} pools three demonstration sets; changes relative to the original trace and expression trace are paired on the same programs.'])
        lines.append('The length-matched annotation controls retain much larger excess than expression demonstrations in both models. Numeric elaboration reduces excess relative to the original trace but leaves a larger effect than source expressions. Token count alone does not reproduce the expression benefit, and adding valid arithmetic accounts for part of it; these two contrasts do not isolate a single mechanism.')
        rows=[]
        for m,d in x['models'].items():
            for kind,r in d.items():rows.append([LABEL[m],kind.replace('_',' '),ci(r['excess_ci95']),ci(r['difference_vs_trace_ci95']),ci(r['difference_vs_trace_expr_ci95'])])
        table(lines,'lllll','Model & Format & Excess & Change vs trace & Change vs expression',rows,
            'Excess name errors and paired changes in percentage points [95\\% interval]. Bootstrap clusters keep all demonstration repeats for each matched program together. These controls assess length and numeric elaboration; they do not by themselves establish how expressions change generation.','tab:round5-formats')
    (ROOT/'paper/tables/round5_followups.tex').write_text('\n'.join(lines)+'\n')

if __name__=='__main__':main()
