#!/usr/bin/env python
"""Put validated error readouts and independent replication in one main-text table."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUMMARY = ROOT / "results/summary"
TABLES = ROOT / "paper/tables"
MODELS = [("olmo2-7b-it", "OLMo-2-7B"), ("llama32-3b-it", "Llama-3.2-3B"),
          ("llama31-8b-it", "Llama-3.1-8B")]


def load(name):
    path = SUMMARY / f"{name}.json"
    data = json.loads(path.read_text())
    if not data.get("validated"):
        raise ValueError(f"unvalidated source: {path}")
    return data


def ci(values, signed=False):
    if values is None:
        return "--"
    sign = "+" if signed else ""
    return f"{100*values[0]:{sign}.1f} [{100*values[1]:{sign}.1f}, {100*values[2]:{sign}.1f}]"


def tabular(columns, header, rows):
    lines = [r"\sbox{\centralbox}{\begin{tabular}{@{}" + columns + r"@{}}", r"\toprule",
             header + r" \\", r"\midrule"]
    lines += [" & ".join(row) + r" \\" for row in rows]
    lines += [r"\bottomrule", r"\end{tabular}}",
              r"\ifdim\wd\centralbox>\textwidth\resizebox{\textwidth}{!}{\usebox{\centralbox}}\else\usebox{\centralbox}\fi"]
    return lines


def main():
    probes = load("round6_crossfit_probes")
    replication = load("round6_identifier_replication")
    cells = json.loads((SUMMARY / "cell_inference.json").read_text())["cells"]
    baseline_path = SUMMARY / "round7_prompt_comparison.json"
    baseline = load("round7_prompt_comparison") if baseline_path.exists() else None
    if baseline and baseline["reference_sha256"] != hashlib.sha256(
            (SUMMARY / "round6_crossfit_probes.json").read_bytes()).hexdigest():
        raise ValueError("prompt comparison refers to a different pre-write release")
    lines = ["% Generated by scripts/83_main_evidence.py from validated summaries.",
             r"\newsavebox{\centralbox}",
             r"\textbf{A. Original names: readouts on actual incorrect sum writes}\\[2pt]"]
    rows = []
    for model, label in MODELS:
        error = probes["models"][model]["pooled"]["lure_write"]
        cell = cells[f"L5/{model}/trace/len-to-sum"]
        row = [label, f"{100*cell['excess']:+.1f}"]
        if baseline:
            comparison = baseline["models"][model]["pooled"]["lure_write"]
            if (comparison["n"], comparison["n_programs"]) != (error["n"], error["n_programs"]):
                raise ValueError("main-table readout cohorts differ")
            row.append(ci(comparison["prompt_accuracy_ci95"]))
        row += [ci(error["accuracy_ci95"]), f"{error['n']} / {error['n_programs']}"]
        rows.append(row)
    header = "Model & Excess (points) & " + ("Prompt (\\%) & " if baseline else "")
    header += "Before write (\\%) & Writes / computations"
    lines += tabular("l" + "r" * (len(rows[0]) - 1), header, rows)
    lines += [r"\\[5pt]\textbf{B. Independent screened names and fresh computations}\\[2pt]"]
    rows = [[label, ci(replication["models"][model]["trace"]["excess_ci95"]),
             ci(replication["models"][model]["trace_expr"]["excess_ci95"]),
             ci(replication["models"][model]["expression_minus_trace_ci95"], signed=True)]
            for model, label in MODELS + [("codegemma-7b-it", "CodeGemma-7B")]]
    lines += tabular("lrrr", "Model & Values only & Operation + value & Paired change", rows)
    (TABLES / "central_evidence.tex").write_text("\n".join(lines) + "\n")
    note = "% The prospective prompt-end comparison has not released results yet.\n"
    appendix = "% No prompt-end results available yet.\n"
    if baseline:
        note = ("Table~\\ref{tab:central}A also compares the final prompt token, before generation, "
                "with the token before the wrong write. Both use the same disjoint training split "
                "and neutral-only fold selection. Differences are paired on the same observed errors "
                "(Appendix~\\ref{app:prompt-comparison}).\n")
        appendix_lines = [r"\section{Prompt-end versus pre-write readouts}", r"\label{app:prompt-comparison}",
            "We fit separate probes at the final token of the complete prompt ending in \\texttt{Trace:}, "
            "before generating any trace token. Tokenization of this prefix is checked against the "
            "original continuation. Training computations, demonstration sets, SGD recipe and seeds "
            "match the pre-write probes. Each position selects its layer independently using the "
            "same five canonical-computation folds and other folds' neutral labels. Outcome strata "
            "and generated-prefix eligibility are frozen from the previous audit. Intervals use "
            "4,000 paired canonical-computation bootstrap draws and condition on the fixed selectors.",
            r"\begin{table*}[t]", r"\centering\small"]
        rows = []
        for model, label in MODELS:
            for stratum, text in (("lure_write", "sum write"), ("correct_write", "correct write"),
                                  ("other_error", "other error")):
                data = baseline["models"][model]["pooled"][stratum]
                rows.append([label, text, f"{data['n']} / {data['n_programs']}",
                             ci(data["prompt_accuracy_ci95"]), ci(data["prewrite_accuracy_ci95"]),
                             ci(data["prewrite_minus_prompt_ci95"], signed=True),
                             ci(data["prompt_control_accuracy_ci95"])])
        appendix_lines += tabular("llrrrrr", "Model & Write & Rows / computations & Prompt & Before write & Change & Name ID", rows)
        appendix_lines += [r"\caption{Paired true-digit accuracies and prompt-position name-identity controls "
                           r"(\%) [95\% interval]. Change is pre-write minus prompt accuracy in points.}",
                           r"\label{tab:prompt-comparison}", r"\end{table*}"]
        appendix = "\n".join(appendix_lines) + "\n"
    (TABLES / "prompt_comparison_note.tex").write_text(note)
    (TABLES / "prompt_comparison_appendix.tex").write_text(appendix)
    print("wrote central evidence table; prompt comparison available:", bool(baseline))


if __name__ == "__main__":
    main()
